apiVersion: apps/v1
kind: Deployment
metadata:
  name: dating-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dating-backend
  template:
    metadata:
      labels:
        app: dating-backend
    spec:
      containers:
        - name: backend
          image: your-registry/dating-backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: dating-backend-svc
spec:
  selector:
    app: dating-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000